baseURL = "/"
languageCode = "en-us"
title = "Alphabit Fund Website"
theme = "alphabit"
publishDir = "docs"

[params]
    name = ""
    description = ""
	phone = "1.800.000.001"
    favicon = "images/favicon-32x32.png"
    DateForm = ""

[[menu.main]]
    name = "Our Philisophy"
    url = "/#philisophy"
    weight = 1
[[menu.main]]
    name = "The Strategy"
    url = "/#strategy"
    weight = 2
[[menu.main]]
	name = "Team Members"
	url = "/#members"
	weight = 3

[[menu.main]]
	name = "Get In Touch"
	url = "/#contact"
	weight = 4

	
[params.google.analytics]
    trackerID = "GA-000000000-0"

[params.social.facebook]
	title = "facebook"
	url = "https://www.facebook.com/alphabitltd/"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
	
[params.social.twitter]
	title = "twitter"
	url = "https://twitter.com/alphabitltd"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "twitter"
	
[params.social.in]
	title = "linkedin"
	url = "https://www.linkedin.com/company/18050235/"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "linkedin"