baseURL = ""
languageCode = "en-us"
title = "Alphabit Fund Website"
theme = "alphabit"
publishDir = "docs"

[params]
    name = ""
    description = ""
    email = ""
    phone = ""
    address = ""
    year = ""
    background = ""
    favicon = "images/gt_favicon.png"
    DateForm = ""

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownload = true
    showClients = true

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = true
    footerEnableFormWidget = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

[params.google.analytics]
    trackerID = "GA-000000000-0"

[params.social.facebook]
	title = "facebook"
	url = "https://www.facebook.com/"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
	
[params.social.twitter]
	title = "twitter"
	url = "https://www.twitter.com/"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "twitter"
	
[params.social.in]
	title = "linkedin"
	url = "https://www.linkedin.com/"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "linkedin"
	